### ISSUE TITLE
Change the top banner message to the following:

### ISSUE THREAD

**Issue by Rune23** [makerdao/maker-market#113]
Combine the two current messages into a single banner with this text

Welcome to Maker Market! Please excuse the user experience quirks - this is an experimental decentralized exchange that is still under heavy development. To get started, go to **deposit/withdraw** and deposit ETH to turn it into W-ETH (Ethereum Token Standard). After depositing ETH, go to **Trade** and set your allowance (999999 works). When ready you can place new orders or trade existing orders. **Click on an open order on the order book to buy/sell into it**.

**Comment by pimato** [comment]
Hey rune,

do we really need the "Welcome to Maker Market! Please excuse the user experience quirks - this is an experimental decentralized exchange that is still under heavy development." ?

I am currently working on the "get started" part. I thought a pagination would help us to give the instruction more structure.

![bildschirmfoto 2017-01-15 um 09 38 13](https://cloud.githubusercontent.com/assets/5337809/21961301/6929d4ec-db06-11e6-8b1a-623dfd0f3bd3.png)

**Comment by Rune23** [comment]
yeah thats better :)

**Comment by Rune23** [comment]
small changes i think should be included

2: should be "Go to _trade_ and set your _allowance_ before you start trading

3: Place new orders or trade existing orders. _Click on an open order to buy/sell it_

**Comment by Rune23** [comment]
I think Geronimo's version is better than my copypasta

**Comment by pimato** [comment]
discussion is moved to : 
https://github.com/makerdao/maker-market/issues/128
