### ISSUE TITLE
the overflow is messed up in "My Orders"

### ISSUE THREAD

**Issue by apmilen** [makerdao/maker-market#115]
![screen shot 2017-01-12 at 5 03 35 pm](https://cloud.githubusercontent.com/assets/2745728/21914616/4e890348-d8e9-11e6-99e2-9efcd9444c7d.png)

**Comment by elioosesconnaxis** [comment]
@gbalabasquer i fix the spaces between, that's how it would look:

about:blank
![captura de pantalla 2017-01-20 a las 13 43 11](https://cloud.githubusercontent.com/assets/22946832/22159634/9b188142-df20-11e6-9cff-c2fb1b14f3d2.png)

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge.
