### ISSUE TITLE
sync trades from last 24h

### ISSUE THREAD

**Issue by cassiopaia** [makerdao/maker-market#12]
@jorisbontje: 

> Only sync the trade events from the last 24h (last ~6000 blocks); rather than all of them from block 0.
> With metamask processing the entire blockchain is problematic from the genesis block.

ported from [ sync trades from last 24h #102 ](https://github.com/MakerDAO/maker-otc/issues/102)

**Comment by jorisbontje** [comment]
https://github.com/MetaMask/metamask-plugin/issues/503

**Comment by gbalabasquer** [comment]
@jorisbontje We are closing it. With the new volume functionality we need a big portion of the Trade history. Not just last 24hs.
