### ISSUE TITLE
Market paper should round/truncated the price if it is too long

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#121]
![bildschirmfoto 2017-01-19 um 22 18 25](https://cloud.githubusercontent.com/assets/5337809/22125835/8d6700ae-de95-11e6-9c91-64760e3dc3c2.png)

should be maximal three numbers after the period.

**Comment by gbalabasquer** [comment]
@pimato We missed to truncate that. However it should be 5 numbers max as we are using that convention for the rest of places.

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge.

**Comment by pimato** [comment]
@gbalabasquer 

could you make it like this preview: 

![bildschirmfoto 2017-01-24 um 12 42 34](https://cloud.githubusercontent.com/assets/5337809/22245957/d6911cc4-e232-11e6-84a1-236ac8619d21.png)

so the price should have 5 decimals (like in the normal price colume in other tables). The volume should have 2 decimals .
