### ISSUE TITLE
Loading Icon is not aligned vertical

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#122]
![bildschirmfoto 2017-01-19 um 22 44 50](https://cloud.githubusercontent.com/assets/5337809/22126699/12e00ae8-de99-11e6-82a7-b9e7f39c4349.png)

loading icon should be aligned vertical in the cell

**Comment by elioosesconnaxis** [comment]
@gbalabasquer i fix this, that's how it would look:

![captura de pantalla 2017-01-20 a las 15 16 01](https://cloud.githubusercontent.com/assets/22946832/22160310/96ee90f4-df23-11e6-82e0-7d7ed796fdc3.png)

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge.

**Comment by pimato** [comment]
@elioosesconnaxis  @gbalabasquer 


![bildschirmfoto 2017-01-24 um 12 49 04](https://cloud.githubusercontent.com/assets/5337809/22246167/bbd4ca60-e233-11e6-8581-2624f46642b7.png)

could you also align it horizontal in the cell ? It doesn't look that good if it is on the right.

**Comment by elioosesconnaxis** [comment]
@gbalabasquer @pimato i fix this, that's how it would look:

![captura de pantalla 2017-01-24 a las 11 19 58](https://cloud.githubusercontent.com/assets/22946832/22250814/1b62cfa2-e227-11e6-8c12-9bdacef6af0f.png)
