### ISSUE TITLE
Add SNGLS and 1ST tokens

### ISSUE THREAD

**Issue by Rune23** [makerdao/maker-market#123]
Particularly 1ST is important because it currently doesn't have ANY exchange at all, and some of the presale buyers are pissed about this. Would be a big win if we could fix the drama. Just look at how mad this dude is https://www.reddit.com/r/ethereum/comments/5oxbvf/is_competitivecasual_an_oxymoron_firstblood_blog/dcn4714/

**Comment by Rune23** [comment]
btw just to be clear i am not saying this should be pushed into the current iteration, but rather it should be for the next one when this one has shipped

**Comment by Rune23** [comment]
okay looks like 1ST does have exchanges after all, it just wasnt listed on CMC yet but has been now: http://coinmarketcap.com/assets/first-blood/#markets

**Comment by nanexcool** [comment]
@Rune23 1ST is added in http://maker-market.surge.sh/#trade/W-ETH/1ST

SNGLS needs more testing since it uses 0 decimals.

**Comment by nanexcool** [comment]
@Rune23 added SNGLS as well: http://maker-market.surge.sh/#trade/W-ETH/SNGLS

Since SNGLS uses no decimals, we still need to adapt the UI a bit to disallow buying/selling fractions of SNGLS
