### ISSUE TITLE
the new GUI wont properly load in mist without an authorized account

### ISSUE THREAD

**Issue by Rune23** [makerdao/maker-market#127]
This could cause some user confusion - basically what happens is if you dont authorize an account the GUI just gets stuck with the blue circles and never loads, but as soon as you authorize an account it will work.

**Comment by gbalabasquer** [comment]
@Rune23 @pimato What do you guys suggest? Some kind of message to notice the user the need to authorize an account?

**Comment by Rune23** [comment]
Yes that's probably the best option

**Comment by pimato** [comment]
@Rune23 could you make a screenshot of how it looks like on mist if you don't authorize an account ? So I can work on it ? And can we distinguish if we are using mist or chrome + metamask ?

**Comment by gbalabasquer** [comment]
@pimato It basically keeps all the loading wheels showing.
So the markets loading, the chart loading and the big loading.

The difference between Metamask and Mist is in Metamask you always have an account assigned when in Mist not. So if you do not have an account assigned the toke requests can not be complicated as can not get your balance and your allowance.
I can get you a screenshot tomorrow.

**Comment by gbalabasquer** [comment]
@pimato 

![image](https://cloud.githubusercontent.com/assets/12644398/22299019/5712a074-e301-11e6-92cf-ea540108c550.png)

**Comment by pimato** [comment]
@Rune23  could you write me a message regarding the missing authorized account ?

@gbalabasquer could we distinguish if a user is browsing mkr.market via mist or metamask?
So if a user is using mist and has not authorized an account, he should only see the header of the page with a message.

**Comment by gbalabasquer** [comment]
@pimato We can know if there is account authorized or not.
So if there is not account we should show that message.

**Comment by nanexcool** [comment]
Up for testing at http://maker-market.surge.sh/#trade/W-ETH/MKR

Now it'll show this message...

![image](https://cloud.githubusercontent.com/assets/52510/22312862/992caca2-e338-11e6-9fb4-0e69d3966b99.png)
