### ISSUE TITLE
add GNT transfer possibility

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#130]
we should add the possibility to transfer unwrapped GNT tokens.

![bildschirmfoto 2017-01-22 um 18 47 33](https://cloud.githubusercontent.com/assets/5337809/22184519/75046016-e0d3-11e6-8e00-15e3e5d12b5d.png)

**Comment by gbalabasquer** [comment]
@pimato @zandy We are working on this. We actually found a bug on the transfer section. So working to refactor it a bit. Will let you know when is ready to be tested.

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge.
