### ISSUE TITLE
Loading market-history has a glitch

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#132]
somehow, there is a square in the header of the table : 

![bildschirmfoto 2017-01-24 um 12 59 53](https://cloud.githubusercontent.com/assets/5337809/22246637/fa321bda-e235-11e6-8710-7346838e2d68.png)

**Comment by elioosesconnaxis** [comment]
@gbalabasquer  @pimato  i fix this, that's how it would look:

![captura de pantalla 2017-01-24 a las 12 22 38](https://cloud.githubusercontent.com/assets/22946832/22253306/e824099a-e22f-11e6-9290-058b1fa5d471.png)
