### ISSUE TITLE
Message not showing correctly in My Orders

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/maker-market#133]
![image](https://cloud.githubusercontent.com/assets/12644398/22247421/7f0600d8-e218-11e6-85e7-13660d3a256f.png)

**Comment by elioosesconnaxis** [comment]
@gbalabasquer i fix this, that's how it would look:

![captura de pantalla 2017-01-24 a las 11 32 36](https://cloud.githubusercontent.com/assets/22946832/22251324/1e443b64-e229-11e6-83a1-bf79538160e7.png)
