### ISSUE TITLE
My Bid Disappeared

### ISSUE THREAD

**Issue by kevinduckworthjr** [makerdao/maker-market#138]
Tonight I was using MetaMask and placed a bid on Maker Market (W-ETH for MKR). The bid went through and showed up as pending on both Buy Orders and My Orders. But when I refreshed the page, my bid disappeared. Now the bid is not listed (and was not filled) and my W-ETH token amount is still reduced as if the order went through.

I refreshed MetaMask multiple times but my bid has disappeared.

My deposit to Maker Market was 

0xa1422109619d73e355c68f1a8ee74ad1d478d622398f1188ede2c963ff8c73be

The transaction (which is not registering on Etherscan for some reason) in question is  

0x7942e47e5961b262199cfffa11b73a80cba33dc5fdff23f732051e4b3892c6d4

**Comment by gbalabasquer** [comment]
@kevinduckworthjr apparently the tx went wrong that is why you couldn't see it in etherscan. However you did not lose any of your W-ETH.
You did mention that this is your deposit: https://etherscan.io/tx/0xa1422109619d73e355c68f1a8ee74ad1d478d622398f1188ede2c963ff8c73be

That means you deposited 189.09848 Ether, then 189.09848 W-ETH.

If you check your actual balance: https://etherscan.io/token/0xecf8f87f810ecf450940c9f60066b4a7a501d6a7?a=0xfd42d6606d0f74276af3b67f77088d9bf8bb9e9b is exactly the same.

![image](https://cloud.githubusercontent.com/assets/12644398/22332904/03a5c7d4-e3b2-11e6-887b-64a2e610cbf0.png)

**Comment by kevinduckworthjr** [comment]
@gbalabasquer.  Thanks!  I should be able to re-bid my W-ETH for MKR (or another token) then,  no?  I'll try and let you know if I have any issues.

**Comment by gbalabasquer** [comment]
@kevinduckworthjr yes, you can try again.
