### ISSUE TITLE
left textfield text should have the same padding as the right text

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#142]
The left text is still aligned with the underline, it should have the same margin as the right text : 

left (wrong) : 

![bildschirmfoto 2017-01-26 um 15 40 54](https://cloud.githubusercontent.com/assets/5337809/22335225/2349cb68-e3de-11e6-84b1-75eabac7dc65.png)

right(good):

![bildschirmfoto 2017-01-26 um 15 41 04](https://cloud.githubusercontent.com/assets/5337809/22335233/2a9a4a5a-e3de-11e6-9e6c-eb773e1762d5.png)

**Comment by gbalabasquer** [comment]
@pimato I need to know which margin you want to put on the left.
For the case on the right the margin depends on how long is the token name (As they are always aligned where the token name starts)

**Comment by pimato** [comment]
padding-left: 13px

**Comment by pimato** [comment]
- Could you add the same padding on the right Token Indicator of the Textfield like we implemented it in the Buy/Sell Order widget ?

<img width="942" alt="bildschirmfoto 2017-01-31 um 22 57 40" src="https://cloud.githubusercontent.com/assets/5337809/22486194/d3efa3c4-e808-11e6-89fc-50fe9ae30e48.png">

This is how it should look like : 

<img width="469" alt="bildschirmfoto 2017-01-31 um 22 57 50" src="https://cloud.githubusercontent.com/assets/5337809/22486204/dd69df28-e808-11e6-9103-c7e202448546.png">

**Comment by gbalabasquer** [comment]
@pimato there is not actually right padding on the sell/buy widgets. It is just an specified width for the token text. The text alignment is to the left and then depending how long is the token the free space on the right. In the case of deposit and withdraw the token is always the same for all the rows  so we can give some right padding. Then I need to see which number would make it looks similar than the other but can not know an exact number of pixels. Maybe you can let me know which one you want to add.

**Comment by pimato** [comment]
@gbalabasquer I think we put a 13 pixel padding to the left (for the left text in the textinputfield). So why not doing the same here ?

**Comment by gbalabasquer** [comment]
@pimato makes sense.
