### ISSUE TITLE
New Order modal - allow to edit volume and total

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/maker-market#147]

**Comment by pimato** [comment]
After a user is edited his total buy order, we should clean the buy/sell widget. After I created a buy order the buy widget is still looking like this:

<img width="467" alt="bildschirmfoto 2017-01-31 um 23 16 43" src="https://cloud.githubusercontent.com/assets/5337809/22486848/76a1a430-e80b-11e6-92b6-66e629e8d08e.png">
