### ISSUE TITLE
mkr.market isn't availible via some internet providers.

### ISSUE THREAD

**Issue by sant9ga** [makerdao/maker-market#158]
Some internet-providers in Russia doesn't load the page at all. I've been made to use VPN or proxy. My friend in Austria has the same issue.
There are no errors at browsers, they just show "The connection has timed out" notification after couple of minutes loading.

**Comment by sant9ga** [comment]
And http://maker-market.surge.sh is available.

**Comment by pimato** [comment]
@sant9ga in the future, we will not use mkr.market anymore. You should try the new website oasisdex.com . Also, as soon as it is possible to register a .eth domain on the ENS, we will remove mkr.market and oasisdex.com. If you have any problems, please also contact us on chat.makerdao.com.
