### ISSUE TITLE
Sell orders mixed up

### ISSUE THREAD

**Issue by seriouslylost** [makerdao/maker-market#159]
![mkrmarket170201](https://cloud.githubusercontent.com/assets/16877081/22498024/035a5224-e856-11e6-92bc-295b0356d2cd.png)

see picture. The highest price is on top, not the lowest. you fix?

**Comment by pimato** [comment]
same for me,

also the market graph is looking weird too : 

<img width="462" alt="bildschirmfoto 2017-02-01 um 08 25 20" src="https://cloud.githubusercontent.com/assets/5337809/22498344/0d75e0a0-e858-11e6-9722-00167cfe74c2.png">
