### ISSUE TITLE
changing my allowance to 1.997 w-eth stuck on pending

### ISSUE THREAD

**Issue by ColinLeath** [makerdao/maker-market#161]
may be a metamask issue-- their replay transaction option doesn't do anything.

but I don't see any way to cancel it and start again.

**Comment by gbalabasquer** [comment]
Hi @ColinLeath it was probably a Metamask issue. Can't you just enter to mkr.market again and set up the allowance via the UI?

**Comment by kumavis** [comment]
it doesnt look like the tx was ever published, not sure why

**Comment by ColinLeath** [comment]
I imported my account into a new browser this morning and was able to set the allowance.
I initially wasn't able to set the allowance because I didn't have ether in the account to pay for the transaction. After adding more ether, I tried to set the allowance again and that was when it got stuck on pending.

the network was the main network.
the account /address was just created earlier that day with metamask.
so, I guess, I was trying to sign it with metamask using the mkr.market UI.
