### ISSUE TITLE
Show more/all trades

### ISSUE THREAD

**Issue by cassiopaia** [makerdao/maker-market#20]
@jorisbontje: 

> amans on slack requested the feature to show more trades from the history than just the last 10;
> I can see two options for this:
> 1) we add a "Show more/all trades" link which removes the limit to the filter
> 2) we add an "export to CSV" and allow the user to download the raw data; not sure if this is possible  > to do client side.

(ported from [ Show more/all trades #125 ](https://github.com/MakerDAO/maker-otc/issues/125)

**Comment by cassiopaia** [comment]
@pimato: 

>  in Poloniex they have both options and I use both of them. This implementation would be perfect!

**Comment by freekp** [comment]
Update this with the current master branch.
Is this superseded by #22 since this only adds "more orders" to last trades?
