### ISSUE TITLE
 Add frontend to Token Auction

### ISSUE THREAD

**Issue by cassiopaia** [MakerDAO/maker-market#21]
@jorisbontje:

> https://github.com/nexusdev/token-auction
> https://github.com/rainbeam/token-auction

(ported from [ Add frontend to Token Auction #126 ](https://github.com/MakerDAO/maker-otc/issues/126))

**Comment by cassiopaia** [comment]
@jorisbontje:

> Approach to be discussed with rain

**Comment by cassiopaia** [comment]
@rainbeam:

> Repo migrated to https://github.com/makerdao/token-auction

**Comment by jorisbontje** [comment]
See https://github.com/MakerDAO/token-auction/issues/4
