### ISSUE TITLE
UI disables selecting same token for buy and sell

### ISSUE THREAD

**Issue by cassiopaia** [makerdao/maker-market#24]
@p-s-dev:

>Currently MM allows the same asset/token to be selected for both the Buy and Sell side of a trade.  This might result in a user accidentally doing something like selling 2eth for 1eth.

>Proposed fix options: 
> - When an asset is select from either the buy or sell side, some javascript action will remove it from the >other side.
> - Or add a validation check so that if an asset is selected and it is the same as the other side of the trade, disable the buttons for making a new trade.

---
(ported from [ UI disables selecting same token for buy and sell #131 ](https://github.com/MakerDAO/maker-otc/issues/131))

**Comment by sunfeld** [comment]
Added an error message after token select boxes to indicate that the token pair does not exist. Also disabled the 'submit order' button if the tokens are the same.
