### ISSUE TITLE
unstable network connection w/ MetaMask

### ISSUE THREAD

**Issue by inmathwetrust** [makerdao/maker-market#33]
So i had not previously experienced this problem using the chrome extension. With the release of contract 0x5c353a8dde7c400a84a673719cc0a0800108ea73 The network connection pulsates intermittently back and forth from Network: main (ready) [?] to Network: main (out of sync, waiting for synchronization) [?].
I did encounter such issue in the past using the parity-ui. Are all MetaMask users affected by this or is there something wrong locally with my setting?

**Comment by jorisbontje** [comment]
Thanks for your report. I haven't seen this myself with MetaMask (I did see this with Parity though). As they are in public beta now, I could imagine their servers to be getting heavy load which could be a potential cause.

**Comment by jorisbontje** [comment]
I can reproduce the issues with MetaMask. I had a discussion with kumavis from MetaMask about possible causes this morning, and will further investigate.

**Comment by jorisbontje** [comment]
I noticed that their network is occasionally returning old blocks; this probably is caused by the server farm they are deploying; where some of the nodes are lagging behind. I'll create an upstream issue for this while in the meanwhile see if I can detect and filter these old blocks.

**Comment by jorisbontje** [comment]
https://github.com/MetaMask/metamask-plugin/issues/504

**Comment by jorisbontje** [comment]
@inmathwetrust I deployed a workaround for this, can you verify the stability of MetaMask?

**Comment by inmathwetrust** [comment]
so far so good @jorisbontje ! 
will report back to you after more hours of play.

**Comment by jorisbontje** [comment]
Problem is solved upstream.
