### ISSUE TITLE
Unable to connect mkr.market to Ethereum w/ Mist

### ISSUE THREAD

**Issue by anttiantti** [makerdao/maker-market#34]
I have Mist running, but when I go to mkr.market it gives me an error 'Ethereum not found'.

![mist](https://cloud.githubusercontent.com/assets/20643638/17147886/634da72c-536d-11e6-871f-59f38a638a96.jpg)
![market](https://cloud.githubusercontent.com/assets/20643638/17147892/6a05f15a-536d-11e6-80fc-a26f9d9f9591.jpg)
![market_console](https://cloud.githubusercontent.com/assets/20643638/17147905/809409a2-536d-11e6-87dd-0635292ba8fa.jpg)

**Comment by jorisbontje** [comment]
Thanks for the provided screenshots; a couple observations that might help you:
1) You should open https://mkr.market from inside Mist (by clicking on the address bar and typing the URL there), then it will be able to connect your DApp to Ethereum. Instead you seem to have opened up https://mkr.market from inside your regular (chrome) browser; this won't be compatible with Mist.
2) Your Ethereum node has 0 peers and was last synced 7 hours ago. Ensure it is well connected and fully synced for maker market to work.

**Comment by anttiantti** [comment]
Using Mist instead of Chrome for typing in the address seems to do the trick. I was clearly a bit lost there. Thanks for your help!

**Comment by jorisbontje** [comment]
@anttiantti any suggestion how to improve this somewhere in the user interface / documentation / etc to make it more obvious for the next person?

**Comment by anttiantti** [comment]
So the problem was I did not realise you should type the URL into the Mist browser (even though it has the word 'browser' in the name). I guess that would not have happened that easily if Mist looked more like other browsers. I had a look at Chrome, Firefox and Safari. I noticed two things they all have in common.

1. there is a rectangular box on top all the way from left to right. Where as in Mist this box does not reach the left side b/c there's a box on the left from top to bottom. (the one containing browse and wallet buttons)

2. at the top theres a rectangular field for typing in the URL. The URL is always aligned to the left. In Mist the URL is centered.

Regarding interface I'd say these two modifications would make a difference.

Regarding documentation I'd say watching the video (https://www.youtube.com/watch?v=6Gf_kRE4MJU) on Metamask website gave a rather good understanding on how the Metamask extension should work and then realise when it was not working properly. I was not able to find anything like that for Mist though. What I found was some rather technical youtube videos from earlier Mist versions.

So maybe having a 3 min video introducing what Mist is, what it can be used for and how to do the basic things could help. Also on https://mkr.market, when no Ethereum is found there's a list of clients you can use: Mist, Metamask, etc.. The line Where it says Mist: 'Mist browser, version 0.8.0 or above.' could be extended to say: 'Mist browser, version 0.8.0 or above. (use to connect to Ethereum and browse https://mkr.market)'

**Comment by jorisbontje** [comment]
@anttiantti thanks for your suggestions. I have improve the wording on the "Ethereum not found" screen:

![screenshot 2016-07-27 14 32 22](https://cloud.githubusercontent.com/assets/620959/17175296/11e1871a-5407-11e6-8b3b-f899f8d689c0.png)
