### ISSUE TITLE
Disallow transfer of ETH tokens

### ISSUE THREAD

**Issue by rainbeam** [makerdao/maker-market#37]
I think current users find it non obvious what ETH-tokens are and how they relate to ETH. 

I think the UI should disallow transfer of ETH-tokens and only allow deposit / withdraw.

The motivating user story would be someone doing some trades and then transferring ETH-tokens to an exchange address. The exchange won't receive the actual ether and would have to manually withdraw from the wrapper, which they may not be willing to do.

Other tokens are fine, it's just ETH that is the problem.

An alternative would be to make transfer of ETH tokens actually do a withdraw-then-send.

**Comment by jorisbontje** [comment]
@rainbeam I have disabled the ETH tokens for transfers and tried to improve the wording for the ETH deposit / withdrawals. More suggestions welcome!

**Comment by rainbeam** [comment]
Maybe just "Deposit / Withdraw ETH"

**Comment by jorisbontje** [comment]
Closing since this is implemented.
