### ISSUE TITLE
Click events not working on Firefox

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/maker-market#4]
As reported by @xeroc:
> I can't cancel my sell orders .. when clicking the X nothing happens
> no javascript messages ..  
> no transaction produced ..
> well here .. we go .. No i sold some MKR .. :disappointed:
> works with chrome it seems
> but not reliably .. sometimes I don't see a popup at all
> Firefox ..
> fairly recent

**Comment by sunfeld** [comment]
Cannot reproduce this error, but if it persists it could be because of the combination of these lines in orderrow.js
```event.preventDefault();
event.stopPropagation();```
