### ISSUE TITLE
Show "My Trades" history

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/maker-market#42]
Similar to "Last Trades", but showing all your trades.

**Comment by jorisbontje** [comment]
Depends on an extension of the `Trades` event with `buyer` and `seller` data. https://github.com/makerdao/maker-otc/issues/135#issuecomment-240430948

**Comment by rainbeam** [comment]
+1 but is it possible to do this via the erc20 `Transfer` events? Are they nested beneath the `Trade` event in the log hierarchy at all?
