### ISSUE TITLE
order matching keeper task

### ISSUE THREAD

**Issue by cassiopaia** [makerdao/maker-market#5]
Bot/ keeper task that connects to the exchange and performs (arbitrage) trades.

* [ ] Study https://github.com/nexusdev/keeper
* [ ] Discuss with dbrock how to integrate this with keeper

(ported from https://github.com/MakerDAO/maker-otc/issues/8)

**Comment by cassiopaia** [comment]
Development for this is happening in https://github.com/BlockChainCompany/maker-market-matcher

**Comment by jorisbontje** [comment]
Moved to https://github.com/BlockChainCompany/maker-market-matcher
