### ISSUE TITLE
Rename ETH Token Wrapper to WETH in the UI

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/maker-market#50]
This is a proposal made in https://chat.makerdao.com/channel/marker-market please vote (thumbs up / down)

**Comment by jorisbontje** [comment]
Using https://github.com/nexusdev/weth/blob/master/weth.sol as dependency

**Comment by gbalabasquer** [comment]
@jorisbontje @nmushegian @apmilen 
Can we finally change the name? So we keep consistent with GNT.

Should we use:
WETH and WGNT or use ETHW and GNTW?

**Comment by nmushegian** [comment]
W-ETH W-GNT?

**Comment by nanexcool** [comment]
@nmushegian WETH and WGNT is fine. In Etherdelta though it's GNTW. So we have to decide if we keep it consistent with them or just do our own thing.

**Comment by nmushegian** [comment]
X-W choice gives the benefit of appearing next to X in search. 

But also, why not both? They could link to the same market, or the UI could think they are different but point to the same address. Who cares?
