### ISSUE TITLE
Maker Market design implementation

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#58]
# Maker Market
- table header 
  -  should be one even line.
  -  header text color should be #666669 not #a9a8a7
- Every page should have the question button on the right top corner
# BUY/SELL - Page
- Textfield hint-text should have the color #68676B not #838282
- Textfield underline bar should have the color #F5F5F6 not #d4dbdf
- Textfield currency indicator (ETH/MKR) should have the same padding to the input text.
# Market History Page
- align every column (DATE / TYPE / PRICE / MKR / ETH ) properly
- show the PRICE/MKR/ETH column with three digits after the period.
- style the see all/show more button
## Before

![bildschirmfoto 2016-10-02 um 21 12 01](https://cloud.githubusercontent.com/assets/5337809/19023041/00eade6c-88e5-11e6-8de5-3fb67120c5ec.png)
## After

![bildschirmfoto 2016-10-02 um 21 11 45](https://cloud.githubusercontent.com/assets/5337809/19023043/088edf42-88e5-11e6-9a25-80890af6f05d.png)

**Comment by pimato** [comment]
Hey freek, 

the UI is looking better and better, thanks for that.
There are still small changes we need to make : 

![temp](https://cloud.githubusercontent.com/assets/5337809/19407596/23fd3d34-92a7-11e6-9b9f-3509c469c974.png)


1) the Question button is still not on right top corner of the Market History Paper.
2) The column names should have the order Date, Type, Price, ETH,  MKR
2) The column names should be align on the right. Right now they are centered.
3) The font color of the date cells should be #b1b1b3
4) The Button should use the font Montserrat Semi bold
4) The Button should use the font color #4F5362 and the border should use #A8ACB9
5) The rows of the MKR column are not aligned on the right side.
6) The rows of the ETH column are not aligned on the right side.
7) The Headline should have a margin-bottom of 20.

**Comment by pimato** [comment]
![bildschirmfoto 2016-10-15 um 07 32 28 kopie](https://cloud.githubusercontent.com/assets/5337809/19407763/98d1c48c-92ab-11e6-9a4a-744b57f297ed.png)

1) the line is not aligned
2)the deposit/withdraw button should have a little bid more padding on the left and on the right.

**Comment by pimato** [comment]
![test](https://cloud.githubusercontent.com/assets/5337809/19407859/ae941664-92ae-11e6-8cbc-42df82df98a5.png)

1) Question Button should be on the right top corner of the BUY/Sell Paper.
2) Paper background should be #fcfbfb not #fffefe
3) The text of the texfield should be closer to the underscore
3) The text of the textfield should have the color #68676B not #848383.
4) The underscore should have the color #f7f7f8 not #d6dcdf.
5) The button should  use the Semi bold Montserrat edition.
5) inner Text of the button should have a bigger padding for the left and right side.

**Comment by pimato** [comment]
![lala](https://cloud.githubusercontent.com/assets/5337809/19408025/764721ac-92b3-11e6-85f8-6eda6662f3a1.png)

1) Question Button should be on the right top corner of the BUY/Sell Paper.
2) "ETH" Should be renamend in "BALANCE" 
3) we should put a "ETH" on the right side of the number
3) We should change the font color of the number in #b1b0b3
4) There should be an underscore to indicate a Textinputfield.
5) We should put a "ETH" on the right side of the number
6) The "DEPOSIT" Button should be aligned on the bottom right corner
7) But Textinput fields should be aligned vertical centered.

**Comment by gbalabasquer** [comment]
@freekp / @pimato 
Can this issue be closed?

**Comment by pimato** [comment]
@gbalabasquer no, almost nothing was fixed.

**Comment by gbalabasquer** [comment]
@pimato 
Ok, but should we think on assign someone to fix them or with the new UI a lot of this stuff will change? I'm not sure which is the scope of the UI changes.

**Comment by pimato** [comment]
@gbalabasquer almost everything I mentioned above is still present in the new UI Iteration of Maker-Market and should be fixed in the future (since my comments at the beginning of 15th december). The only thing which isn't necessary to fix is the thing with the "Shore More" Button because the button will be gone in the next iteration.

**Comment by pimato** [comment]
@gbalabasquer : Yes we need to assign someone who can fix the UI-bugs, I mentioned above.
