### ISSUE TITLE
Usability issue - I just can't figure it out.

### ISSUE THREAD

**Issue by kayagoban** [makerdao/maker-market#61]
I trust I am not terribly dull.  Even so, I wasn't able to figure out how to create a token sell order.  I tried making an allowance, and succeeded, but afterwards the sell button was still greyed out.

I suggest some more work on the usability front.

**Comment by pimato** [comment]
hey @kayagoban ,

at first, thanks for the feedback. We definitely need to figure out where the problems was. I have a few questions:

1) Do you deposit Ether into the Market ?
2) Do you use Metamask or Mist?

cheers

**Comment by kayagoban** [comment]
Hi.

1) no, trying to deposit DGD
2) Metamask, because geth broke my heart too many times.

**Comment by pimato** [comment]
hey @kayagoban ,

1) DGD is already a ERC20 Token, you don't need to make a deposit into the Maker Market. It sould be already visible.

2) I am still trying to figure out where the problem was. Do you filled every Inputfield with information?

**Comment by kayagoban** [comment]
I think there are some basic assumptions about how the UI works, that they are not being communicated by the interface.

I highly suggest getting a person who regularly uses centralized exchanges, and sit them in front of mkr.market, and watch them try to use it.

I don’t know what it is I’m missing.  But I think that many other people are missing it also, whatever it is.’

Good luck!

**Comment by pimato** [comment]
Hey,

you are right. And your feedback is very important  for us. The new UX Design is very fresh and will need to have a lot of polishing in the next couple of weeks/month. We are constantly working on it.

Thanks for the feedback
pimato
