### ISSUE TITLE
Inverted Sell vs Buy labels on Market History

### ISSUE THREAD

**Issue by ramos-j** [makerdao/maker-market#63]
The labels 'sell' and 'buy' are inverted on the market history. When someone takes a buy order, this is a 'sell' operation, and vice-versa.

**Comment by gbalabasquer** [comment]
Adding what was said in rocket chat:

> take a look at polo's orderbook. this is way more intuitive: your main view is to the left if you want to buy, so you either create a buy order on top or click on a sell order listed below. and your focus is on the right if you want to sell, naturally. MM has it crossed, and it's counterintuitive.
> https://poloniex.com/exchange#btc_eth
> poloniex.com
> Poloniex - Bitcoin/Cryptocurrency Exchange
> also the history is still inverted. I already mentioned this months ago. If someone takes a previously created sell order, this is a buy operation (but the History log shows it as a sell operation).
> for the FAQ, it should definitely explain in bold that there's no order matching. every single first-time user will get confused if not properly informed.

**Comment by gbalabasquer** [comment]
@pimato @ramos-j Do we finally have to do this or this issue can be discarded?

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge. We need to remember to explain this change to the community when we upload to mkr.market.

**Comment by gbalabasquer** [comment]
zandy 5:25 PM
The order type in `My Orders` shouldn't be inverted
and in `Market History` change `TYPE` to `ACTION
