### ISSUE TITLE
Make the Hit boxes for the attached button panel bigger

### ISSUE THREAD

**Issue by apmilen** [makerdao/maker-market#73]
The hitboxes of these buttons is only as big as the contained text, not the entire button. It annoys me all the time.

<img width="462" alt="screen shot 2016-11-21 at 7 56 25 am" src="https://cloud.githubusercontent.com/assets/2745728/20489585/06314698-afc0-11e6-95d2-a9e34d39d99c.png">

Also the button panel below this one on the trade page that allows you to select tokens has a hit box that's slightly too small but not as annoying.

**Comment by gbalabasquer** [comment]
@apmilen 

"Also the button panel below this one on the trade page that allows you to select tokens has a hit box that's slightly too small but not as annoying."

You mean the dropdowns?
