### ISSUE TITLE
Graph support

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/maker-market#75]
Graph support, you can take the graph from https://makerdao.github.io/markets/ or choose your own

**Comment by gbalabasquer** [comment]
@apmilen Do we have any mockup to follow? Or we can add it whatever we want?

**Comment by gbalabasquer** [comment]
@pimato 
Can you help us here?

**Comment by pimato** [comment]
@gbalabasquer , I am already working on it. Will have something in the next days.
