### ISSUE TITLE
Link to Market History

### ISSUE THREAD

**Issue by jorisbontje** [makerdao/maker-market#77]
Add link to https://makerdao.github.io/markets/

**Comment by gbalabasquer** [comment]
@pimato 
Any insight on where add it?

**Comment by pimato** [comment]
I am working on the new Maker-Market Design Iteration. I will include that.

**Comment by gbalabasquer** [comment]
@pimato Are we adding it? Is one of the footer links? btw, we need to add these links.

**Comment by pimato** [comment]
@gbalabasquer : We should use the placeholder Market data as a link to https://makerdao.github.io/markets/ .

**Comment by gbalabasquer** [comment]
@apmilen @pimato Ready to be tested on Surge.
