### ISSUE TITLE
Maker Market not syncing properly

### ISSUE THREAD

**Issue by pimato** [makerdao/maker-market#78]
Hey,

maker market synchronization is rarely reaching 100%. If it is reaching 100% it will try to resync everything again. Seems like a metamask problem:

![bildschirmfoto 2016-11-23 um 14 22 43](https://cloud.githubusercontent.com/assets/5337809/20563346/7ff46cfc-b188-11e6-833d-456e6805ad9b.png)

**Comment by jorisbontje** [comment]
Fixed on the side of MetaMask.
